version: "3.8"

services:
  gui-app:
    build: .
    platform: linux/amd64
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/root/GMD_workspace
    stdin_open: true
    tty: true
